sudo: required
language: generic 
services:
    - docker

before_install:
    - docker build -t kart-projects/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true kart-projects/react-test npm test

after_success:
    - docker build -t kart-projects/multi-client ./client
    - docker build -t kart-projects/multi-nginx ./nginx
    - docker build -t kart-projects/multi-server ./server
    - docker build -t kart-projects/multi-worker ./worker
    # Log in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push it to docker hub
    - docker push kart-projects/multi-client
    - docker push kart-projects/multi-nginx
    - docker push kart-projects/multi-server
    - docker push kart-projects/multi-worker
